# Generated by Django 6.0.4 on 2026-05-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_file_filename_file_updated_at_fileshare_shared_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fileshare',
            name='shared_at',
        ),
        migrations.AddField(
            model_name='file',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='permission',
            field=models.CharField(max_length=10),
        ),
    ]
