# Generated by Django 6.0.4 on 2026-05-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_file_updated_at_remove_fileshare_shared_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
